-- KAN-29 Capital de Trabajo
-- Soporte idempotente para items operativos por carrera.
-- No carga valores de materiales ni los mueve a Datos Institucionales.

CREATE TABLE IF NOT EXISTS public.item_material_insumo (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrera_id integer,
    nombre_item varchar(140),
    categoria_nombre varchar(100),
    unidad_nombre varchar(60),
    cantidad_base numeric(9,4),
    precio_unitario numeric(18,2),
    es_cantidad_fija boolean,
    creado_en timestamptz,
    creado_por_usuario_id integer,
    actualizado_en timestamptz,
    actualizado_por_usuario_id integer,
    esta_activo boolean,
    eliminado_en timestamptz,
    eliminado_por_usuario_id integer
);

ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS carrera_id integer;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS nombre_item varchar(140);
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS categoria_nombre varchar(100);
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS unidad_nombre varchar(60);
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS cantidad_base numeric(9,4);
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS precio_unitario numeric(18,2);
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS es_cantidad_fija boolean;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS creado_en timestamptz;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS creado_por_usuario_id integer;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS actualizado_en timestamptz;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS actualizado_por_usuario_id integer;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS esta_activo boolean;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS eliminado_en timestamptz;
ALTER TABLE public.item_material_insumo ADD COLUMN IF NOT EXISTS eliminado_por_usuario_id integer;

UPDATE public.item_material_insumo
SET nombre_item = 'Item sin nombre'
WHERE nombre_item IS NULL OR btrim(nombre_item) = '';

UPDATE public.item_material_insumo
SET categoria_nombre = 'MATERIALES_SUMINISTROS'
WHERE categoria_nombre IS NULL OR btrim(categoria_nombre) = '';

UPDATE public.item_material_insumo
SET unidad_nombre = 'Unidad'
WHERE unidad_nombre IS NULL OR btrim(unidad_nombre) = '';

UPDATE public.item_material_insumo
SET cantidad_base = 0
WHERE cantidad_base IS NULL;

UPDATE public.item_material_insumo
SET precio_unitario = 0
WHERE precio_unitario IS NULL;

UPDATE public.item_material_insumo
SET es_cantidad_fija = false
WHERE es_cantidad_fija IS NULL;

UPDATE public.item_material_insumo
SET esta_activo = true
WHERE esta_activo IS NULL;

UPDATE public.item_material_insumo
SET creado_en = now()
WHERE creado_en IS NULL;

UPDATE public.item_material_insumo i
SET carrera_id = c.id
FROM (
    SELECT id
    FROM public.carrera
    ORDER BY id
    LIMIT 1
) c
WHERE i.carrera_id IS NULL;

ALTER TABLE public.item_material_insumo ALTER COLUMN nombre_item SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN categoria_nombre SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN unidad_nombre SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN cantidad_base SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN precio_unitario SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN es_cantidad_fija SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN esta_activo SET NOT NULL;
ALTER TABLE public.item_material_insumo ALTER COLUMN creado_en SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.item_material_insumo
        WHERE carrera_id IS NULL
    ) THEN
        ALTER TABLE public.item_material_insumo ALTER COLUMN carrera_id SET NOT NULL;
    ELSE
        RAISE NOTICE 'KAN-29: carrera_id conserva NULL porque no existe una carrera base para completar datos heredados.';
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_item_material_insumo_carrera_id_nombre_item"
    ON public.item_material_insumo (carrera_id, nombre_item);

CREATE INDEX IF NOT EXISTS "IX_item_material_insumo_carrera_id_categoria_nombre"
    ON public.item_material_insumo (carrera_id, categoria_nombre);
