// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAranceles.Infrastructure.Persistence;

#nullable disable

namespace SistemaAranceles.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContextoAplicacion))]
    [Migration("20260327195552_KAN03_Estudiantes")]
    partial class KAN03_Estudiantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccionNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("accion_nombre");

                    b.Property<int?>("EjecutadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ejecutado_por_usuario_id");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadNombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("entidad_nombre");

                    b.Property<DateTime>("EventoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("evento_en");

                    b.Property<string>("ModuloNombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("modulo_nombre");

                    b.Property<string>("ResumenTexto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("resumen_texto");

                    b.Property<string>("ValoresAnterioresJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("valores_anteriores_json");

                    b.Property<string>("ValoresNuevosJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("valores_nuevos_json");

                    b.HasKey("Id");

                    b.HasIndex("EjecutadoPorUsuarioId");

                    b.HasIndex("EventoEn", "ModuloNombre");

                    b.ToTable("auditoria_log", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("FacultadNombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("facultad_nombre");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int>("TotalCiclos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_ciclos");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("carrera", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionCargaDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<decimal>("HorasDocenciaEstandar")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("horas_docencia_estandar");

                    b.Property<decimal>("HorasTecnicoEstandar")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("horas_tecnico_estandar");

                    b.Property<decimal>("ProporcionMgsPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("proporcion_mgs_porcentaje");

                    b.Property<decimal>("ProporcionPhdPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("proporcion_phd_porcentaje");

                    b.Property<int>("ProyeccionEstudiantesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("proyeccion_estudiantes_id");

                    b.HasKey("Id");

                    b.HasIndex("ProyeccionEstudiantesId");

                    b.ToTable("configuracion_carga_docente", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionRetencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("carrera_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<int>("EscenarioProyeccionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("escenario_proyeccion_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<decimal>("EstudiantesPeriodo1")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("estudiantes_periodo_1");

                    b.Property<decimal>("EstudiantesPeriodo2")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("estudiantes_periodo_2");

                    b.Property<int>("ParalelosPeriodo1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paralelos_periodo_1");

                    b.Property<int>("ParalelosPeriodo2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paralelos_periodo_2");

                    b.Property<decimal>("TasaGraduacionPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("tasa_graduacion_porcentaje");

                    b.Property<decimal>("TasaRetencionPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("tasa_retencion_porcentaje");

                    b.Property<int>("TotalCiclos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_ciclos");

                    b.HasKey("Id");

                    b.HasIndex("EscenarioProyeccionId");

                    b.HasIndex("CarreraId", "EscenarioProyeccionId")
                        .IsUnique();

                    b.ToTable("configuracion_retencion", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.CriterioReferenciaRetencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("ConfiguracionRetencionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("configuracion_retencion_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<decimal>("MetaGraduacionPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("meta_graduacion_porcentaje");

                    b.Property<decimal>("MetaRetencionPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("meta_retencion_porcentaje");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionRetencionId")
                        .IsUnique();

                    b.ToTable("criterio_referencia_retencion", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.DetalleProyeccionEstudiantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("CantidadParalelos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad_paralelos");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<int>("NumeroCiclo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_ciclo");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("periodo_academico_id");

                    b.Property<int>("ProyeccionEstudiantesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("proyeccion_estudiantes_id");

                    b.Property<decimal>("TotalEstudiantes")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("total_estudiantes");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoAcademicoId");

                    b.HasIndex("ProyeccionEstudiantesId", "PeriodoAcademicoId", "NumeroCiclo")
                        .IsUnique();

                    b.ToTable("detalle_proyeccion_estudiantes", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.DetalleSimulacionRetencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<int>("NumeroCiclo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_ciclo");

                    b.Property<int>("NumeroPeriodo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_periodo");

                    b.Property<int>("SimulacionRetencionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("simulacion_retencion_id");

                    b.Property<decimal>("TasaAplicadaPorcentaje")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("tasa_aplicada_porcentaje");

                    b.Property<string>("TipoZona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_zona");

                    b.Property<decimal>("ValorEstudiantes")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("valor_estudiantes");

                    b.HasKey("Id");

                    b.HasIndex("SimulacionRetencionId", "NumeroCiclo", "NumeroPeriodo")
                        .IsUnique();

                    b.ToTable("detalle_simulacion_retencion", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.EscenarioProyeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("carrera_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_predeterminado");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId", "Nombre")
                        .IsUnique();

                    b.ToTable("escenario_proyeccion", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.InflacionAnual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("FuenteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fuente_nombre");

                    b.Property<decimal>("PorcentajeInflacion")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("porcentaje_inflacion");

                    b.Property<string>("TipoFuente")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_fuente");

                    b.HasKey("Id");

                    b.HasIndex("Anio")
                        .IsUnique();

                    b.ToTable("inflacion_anual", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.InflacionProyectada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EsAjusteManual")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_ajuste_manual");

                    b.Property<int>("EscenarioProyeccionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("escenario_proyeccion_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("MetodoProyeccion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("metodo_proyeccion");

                    b.Property<decimal>("PorcentajeInflacion")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("porcentaje_inflacion");

                    b.HasKey("Id");

                    b.HasIndex("EscenarioProyeccionId", "Anio")
                        .IsUnique();

                    b.ToTable("inflacion_proyectada", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("EtiquetaPeriodo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("etiqueta_periodo");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("NumeroPeriodo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero_periodo");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "NumeroPeriodo")
                        .IsUnique();

                    b.ToTable("periodo_academico", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccionNombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("accion_nombre");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("ModuloNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("modulo_nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionEstudiantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("AnioBase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anio_base");

                    b.Property<int>("CarreraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("carrera_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<int>("EscenarioProyeccionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("escenario_proyeccion_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<int>("SemanasPorSemestre")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semanas_por_semestre");

                    b.HasKey("Id");

                    b.HasIndex("EscenarioProyeccionId");

                    b.HasIndex("CarreraId", "EscenarioProyeccionId")
                        .IsUnique();

                    b.ToTable("proyeccion_estudiantes", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionRequerimientoDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("ConfiguracionCargaDocenteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("configuracion_carga_docente_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<decimal>("DocentesMgs")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("docentes_mgs");

                    b.Property<decimal>("DocentesParcial")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("docentes_parcial");

                    b.Property<decimal>("DocentesPhd")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("docentes_phd");

                    b.Property<decimal>("DocentesTecnico")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("docentes_tecnico");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("periodo_academico_id");

                    b.Property<decimal>("TotalDocentes")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("total_docentes");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoAcademicoId");

                    b.HasIndex("ConfiguracionCargaDocenteId", "PeriodoAcademicoId")
                        .IsUnique();

                    b.ToTable("proyeccion_requerimiento_docente", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol_id");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("rol_permiso", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.SesionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("EmitidoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("emitido_en");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("expira_en");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenSesion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_sesion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenSesion")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesion_usuario", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.SimulacionRetencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<int>("ConfiguracionRetencionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("configuracion_retencion_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime>("EjecutadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ejecutado_en");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notas");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionRetencionId", "EjecutadoEn");

                    b.ToTable("simulacion_retencion", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actualizado_por_usuario_id");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("correo_institucional");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en");

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creado_por_usuario_id");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("EliminadoPorUsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eliminado_por_usuario_id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("esta_activo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_completo");

                    b.Property<DateTime?>("UltimoAccesoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id");

                    b.HasIndex("CorreoInstitucional")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.AuditoriaLog", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Usuario", "EjecutadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("EjecutadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EjecutadoPorUsuario");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionCargaDocente", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionEstudiantes", "ProyeccionEstudiantes")
                        .WithMany("ConfiguracionesCargaDocente")
                        .HasForeignKey("ProyeccionEstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProyeccionEstudiantes");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionRetencion", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.EscenarioProyeccion", "EscenarioProyeccion")
                        .WithMany("ConfiguracionesRetencion")
                        .HasForeignKey("EscenarioProyeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("EscenarioProyeccion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.CriterioReferenciaRetencion", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionRetencion", "ConfiguracionRetencion")
                        .WithOne("CriterioReferenciaRetencion")
                        .HasForeignKey("SistemaAranceles.Infrastructure.Persistence.Entidades.CriterioReferenciaRetencion", "ConfiguracionRetencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionRetencion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.DetalleProyeccionEstudiantes", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionEstudiantes", "ProyeccionEstudiantes")
                        .WithMany("DetallesProyeccionEstudiantes")
                        .HasForeignKey("ProyeccionEstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoAcademico");

                    b.Navigation("ProyeccionEstudiantes");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.DetalleSimulacionRetencion", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.SimulacionRetencion", "SimulacionRetencion")
                        .WithMany("DetallesSimulacionRetencion")
                        .HasForeignKey("SimulacionRetencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulacionRetencion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.EscenarioProyeccion", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Carrera", "Carrera")
                        .WithMany("EscenariosProyeccion")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.InflacionProyectada", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.EscenarioProyeccion", "EscenarioProyeccion")
                        .WithMany("InflacionesProyectadas")
                        .HasForeignKey("EscenarioProyeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscenarioProyeccion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionEstudiantes", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.EscenarioProyeccion", "EscenarioProyeccion")
                        .WithMany("ProyeccionesEstudiantes")
                        .HasForeignKey("EscenarioProyeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("EscenarioProyeccion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionRequerimientoDocente", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionCargaDocente", "ConfiguracionCargaDocente")
                        .WithMany("ProyeccionesRequerimientoDocente")
                        .HasForeignKey("ConfiguracionCargaDocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracionCargaDocente");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.RolPermiso", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.SesionUsuario", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.SimulacionRetencion", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionRetencion", "ConfiguracionRetencion")
                        .WithMany("SimulacionesRetencion")
                        .HasForeignKey("ConfiguracionRetencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionRetencion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAranceles.Infrastructure.Persistence.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Carrera", b =>
                {
                    b.Navigation("EscenariosProyeccion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionCargaDocente", b =>
                {
                    b.Navigation("ProyeccionesRequerimientoDocente");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ConfiguracionRetencion", b =>
                {
                    b.Navigation("CriterioReferenciaRetencion");

                    b.Navigation("SimulacionesRetencion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.EscenarioProyeccion", b =>
                {
                    b.Navigation("ConfiguracionesRetencion");

                    b.Navigation("InflacionesProyectadas");

                    b.Navigation("ProyeccionesEstudiantes");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.ProyeccionEstudiantes", b =>
                {
                    b.Navigation("ConfiguracionesCargaDocente");

                    b.Navigation("DetallesProyeccionEstudiantes");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.SimulacionRetencion", b =>
                {
                    b.Navigation("DetallesSimulacionRetencion");
                });

            modelBuilder.Entity("SistemaAranceles.Infrastructure.Persistence.Entidades.Usuario", b =>
                {
                    b.Navigation("Sesiones");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
