using SistemaAranceles.Application.DTOs.SueldosPlantaCentral;
using SistemaAranceles.Domain.Entities;

namespace SistemaAranceles.Application.UseCases.SueldosPlantaCentral;

internal static class MapeoDatosInstitucionales
{
    public static DatosInstitucionalesDto AMapeo(DatosInstitucionales d, string? usuarioNombre) => new()
    {
        Id = d.Id,
        Periodo = d.Periodo,
        NumeroEstudiantesUniversidad = d.NumeroEstudiantesUniversidad,
        NumeroDocentesUniversidad = d.NumeroDocentesUniversidad,
        NumeroPersonasPlantaCentral = d.NumeroPersonasPlantaCentral,
        SueldoBasico = d.SueldoBasico,
        Funcional = d.Funcional,
        FondoReserva = d.FondoReserva,
        BeneficioXiv = d.BeneficioXiv,
        BeneficioXiii = d.BeneficioXiii,
        AportePatronal = d.AportePatronal,
        Varios = d.Varios,
        MesesCapitalTrabajo = d.MesesCapitalTrabajo,
        PorcentajeImprevistosInversion = d.PorcentajeImprevistosInversion,
        PorcentajeMatriculaDefault = d.PorcentajeMatriculaDefault,
        PorcentajeBecasInstitucionales = d.PorcentajeBecasInstitucionales,
        SemestresPorAnio = d.SemestresPorAnio,
        MesesOperativosCiclo = d.MesesOperativosCiclo,
        PresupuestoAnualCapacitacion = d.PresupuestoAnualCapacitacion,
        PresupuestoAnualInternacionalizacion = d.PresupuestoAnualInternacionalizacion,
        PresupuestoAnualMarketing = d.PresupuestoAnualMarketing,
        PolizaSeguroEstudiantilAnual = d.PolizaSeguroEstudiantilAnual,
        FuenteInflacion = d.FuenteInflacion,
        AnioBaseProyeccion = d.AnioBaseProyeccion,
        PresupuestoBaseUniversidad = d.PresupuestoBaseUniversidad,
        PresupuestoGobiernoBecas = d.PresupuestoGobiernoBecas,
        PorcentajeInvestigacion = d.PorcentajeInvestigacion,
        PorcentajeVinculacion = d.PorcentajeVinculacion,
        PorcentajeBecasEstudiantes = d.PorcentajeBecasEstudiantes,
        PorcentajeBecasDocentes = d.PorcentajeBecasDocentes,
        TasaInteresFinanciera = d.TasaInteresFinanciera,
        PremioRiesgo = d.PremioRiesgo,
        TmrManual = d.TmrManual,
        UsarTmrManual = d.UsarTmrManual,
        ToleranciaVanArancel = d.ToleranciaVanArancel,
        MargenAproximacionVanArancel = d.MargenAproximacionVanArancel,
        ArancelMinimoBusqueda = d.ArancelMinimoBusqueda,
        ArancelMaximoBusqueda = d.ArancelMaximoBusqueda,
        MaxIteracionesBiseccion = d.MaxIteracionesBiseccion,
        PorcentajeFinanciadoPrestamo = d.PorcentajeFinanciadoPrestamo,
        PorcentajeFinanciadoConvenio = d.PorcentajeFinanciadoConvenio,
        NombreEntidadPrestamo = d.NombreEntidadPrestamo,
        NombreEntidadConvenio = d.NombreEntidadConvenio,
        TasaInteresAnualPrestamo = d.TasaInteresAnualPrestamo,
        PlazoPrestamoMeses = d.PlazoPrestamoMeses,
        MasaSalarialMensual = d.MasaSalarialMensual,
        TotalMensualPlantaCentral = d.TotalMensualPlantaCentral,
        TotalAnualPlantaCentral = d.TotalAnualPlantaCentral,
        RatioAdminPorDocente = d.RatioAdminPorDocente,
        CostoPlantaCentralPorEstudianteAnual = d.CostoPlantaCentralPorEstudianteAnual,
        FechaActualizacion = d.FechaActualizacion,
        ActualizadoPorUsuarioId = d.ActualizadoPorUsuarioId,
        ActualizadoPorUsuarioNombre = usuarioNombre,
        FuenteNotas = d.FuenteNotas,
    };
}
